// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfteqignfqyhnxtawcko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmdGVxaWduZnF5aG54dGF3Y2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDI3MzQsImV4cCI6MjA1OTE3ODczNH0.mk3nppXs6xGaD00uDJa3AqvtnCX_ugV_laxT-A1xM70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);